VERSION --global-cache 0.7
IMPORT github.com/earthly/lib/rust:2.2.10 AS rust

FROM rust:slim-buster
WORKDIR /libs/filter

# build creates the binary target/release/filter
build:
    # Cargo UDC adds caching to cargo runs.
    # See https://github.com/earthly/lib/tree/main/rust
    DO rust+INIT --keep_fingerprints=true
    COPY --keep-ts --dir src Cargo.toml .
    DO rust+CARGO --args="build --release --lib" --output="release/[^/\.]+"
    SAVE ARTIFACT target filter

# test runs the tests present in the package
test: 
    FROM +build
    RUN cargo test

# docker creates docker image filter:latest
docker:
    FROM debian:buster-slim
    COPY +build/filter filter
    EXPOSE 9091
    ENTRYPOINT ["./filter"]
    SAVE IMAGE filter:latest