VERSION --global-cache 0.7
IMPORT github.com/earthly/lib/rust:2.2.10 AS rust

deps:
    LOCALLY
    SAVE ARTIFACT ../../libs/filter src/libs/filter 
    SAVE ARTIFACT ../ingest/ src/services/ingest
    SAVE ARTIFACT ./ src/services/cleanup
    SAVE ARTIFACT ../../Cargo.toml src/Cargo.toml

build:
    FROM rust:slim-buster
    COPY --dir +deps/src .
    WORKDIR src
    DO rust+INIT --keep_fingerprints=true
    DO rust+CARGO --args="build --release --bin cleanup" --output="release/[^/\.]+"
    SAVE ARTIFACT target/release cleanup


# test runs the tests present in the package
test: 
    FROM +build
    RUN cargo test

# docker creates docker image cleanup:latest
docker:
    FROM +build
    ENTRYPOINT ["./cleanup"]
    SAVE IMAGE cleanup:latest
